/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "EmailQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ResendApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ResendDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WeatherAppApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "WeatherAppApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WeatherAppTable": {
      "tableName": string
      "type": "aws.dynamodb/table.Table"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}